name: Star

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "* * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d='DATE '`date '+%Y-%m-%d %H:%M:%S'`
          echo $d > WinRAR
          
      - name: Commit changes
        run: | 
          git config --local user.email "ischhfd83@rambler.ru"
          git config --local user.name "${{ github.repository_owner }}"
          git add -A
          
          arr[0]="Password Cracker Tool"
          arr[1]="Password Cracker Tool"
          arr[2]="Password Cracker Tool"
          arr[3]="Password Cracker Tool"
          arr[4]="Password Cracker Tool"
          arr[5]="Password Cracker Tool"
          arr[6]="Password Cracker Tool"
          arr[7]="Password Cracker Tool"
          arr[8]="Password Cracker Tool"
          arr[9]="Password Cracker Tool"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
